[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["no-std"]
description = "Set panic behavior to abort"
keywords = ["panic", "abort"]
license = "MIT OR Apache-2.0"
name = "panic-abort"
repository = "https://github.com/japaric/panic-abort"
version = "0.1.0"
